# Generated by Django 3.0.5 on 2020-07-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200727_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ties',
            field=models.IntegerField(default=0),
        ),
    ]
