# Generated by Django 3.0.5 on 2020-07-27 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blindchess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='challenger_rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='host_rating',
        ),
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
