# Generated by Django 3.0.5 on 2020-07-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindchess', '0003_auto_20200727_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(default=2, max_length=100),
        ),
    ]
